apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hetchfund.capital-ca
  namespace: ingress-nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  secretName: hetchfund.capital-ca
  dnsNames:
  - apis.hetchfund.capital
  - www.hetchfund.capital
  - hetchfund.capital
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer