apiVersion: apps/v1
kind: Deployment
metadata:
  name: translator
  namespace: ingress-nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
  labels:
    app: translator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: translator
  template:
    metadata:
      labels:
        app: translator
    spec:
      containers:
      - name: translator
        image: registry.digitalocean.com/hetchfundcapital/translator:latest
        ports:
        - containerPort: 4001
        env:
          - name: SELF_ENDPOINT
            value: https://apis.hetchfund.capital/translator

          - name: OE_KEY
            valueFrom:
              secretKeyRef:
                name: translator-environment
                key: OE_KEY
      imagePullSecrets:
        - name: do-registry